### ISSUE TITLE
关于cane.py 代码中的compute_loss函数设置有些疑问

### ISSUE THREAD

**Issue by milamila56** [thunlp/CANE#11]
1. 从代码中看temp_loss=rho1*(p1+p2)+rho2*(p3+p4)+rho3*(p5+p6)+rho3*(p7+p8)
应该是rho1*Ltt + rho2*Lss + rho3*(Lst + Lts），论文里面超参似乎不是这么设置的，复现应该以哪个为准呢？

不知道理解的对不对，请指教，谢谢！

**Comment by chi0612** [comment]
是的啊 我也好奇这个问题

**Comment by tucunchao** [comment]
负责实现本篇论文代码的共同一作Han Liu提供的代码实现，表示向量的计算方式以及loss的系数使用方式与论文不一致，Han Liu也一直没有进行回复该问题。所以我们在19年在Han Liu提供的代码和数据基础之上，提交了一些commits，进行了部分代码bug和数据的修复，目前最新版的实验结果已提交至readme中，供参考，请以代码中的超参为准。
