### ISSUE TITLE
How  do I reproduce the results in the paper?

### ISSUE THREAD

**Issue by tonygracious** [thunlp/CANE#16]
When I am running your code for cora dataset with 15% sampled edges and rho1=1.0, rho2=1.0 & rho3=0.3 I am getting an AUC of 0.8495803744351195 which doesn't matches the paper. What should I do?

**Comment by chendh16** [comment]
If you change the code in train.py at line 79 _(em=list(convA[i])+list(TA[i]))_ and line 82 _(em=list(convB[i])+list(TB[i]))_ to _(em=list(TA[i]))_ and _(em=list(TB[i]))_, maybe you can get the results reported in the paper lol...

**Comment by lilybud** [comment]
> If you change the code in train.py at line 79 _(em=list(convA[i])+list(TA[i]))_ and line 82 _(em=list(convB[i])+list(TB[i]))_ to _(em=list(TA[i]))_ and _(em=list(TB[i]))_, maybe you can get the results reported in the paper lol...

可是这样改的意义是什么？TA[i]和TB[i]似乎只有在最开始的时候随机初始化了~
