### ISSUE TITLE
关于相互关注向量

### ISSUE THREAD

**Issue by prejefferson** [thunlp/CANE#19]
您好！请问在代码里，生成了每个节点的相互关注表示，但是最后求了平均，写入了embed,txt文件，并求出AUC，但是论文里最后进行节点分类时，却说求平均操作是为了获得context-free embedding，请问，这是什么原因呢,是不是代码里的嵌入是为了算分类的嵌入？还是我理解错了？

**Comment by tucunchao** [comment]
负责实现本篇论文代码的共同一作Han Liu提供的代码实现，最终表示向量的计算方式与论文不一致，这也导致了AUC的计算方式与论文不一致，Han Liu也一直没有回复该问题。所以我们在19年在Han Liu提供的代码和数据基础之上，提交了一些commits，进行了部分代码bug和数据的修复，目前最新版的实验结果已提交至readme中，供参考。若您计算了context-aware embedding的auc结果，欢迎提交pr。
