### ISSUE TITLE
关于得到的表示向量

### ISSUE THREAD

**Issue by chi0612** [thunlp/CANE#21]
论文中提到最后的节点表示向量应该是结构嵌入与文本嵌入相结合的形式，但代码中在train.py进行写入时只写入了TA，TB代表的结构嵌入，而没有写入文本嵌入，所以导致即使设定了最后的表示向量是200维，但写入后的文件仍然只有100维。不知道我说的对吗，或者我哪块理解有问题。

**Comment by tucunchao** [comment]
负责实现本篇论文代码的共同一作Han Liu提供的代码实现，表示向量的计算方式与论文不一致，Han Liu也一直没有进行回复该问题。所以我们在19年在Han Liu提供的代码和数据基础之上，提交了一些commits，进行了部分代码bug和数据的修复，目前最新版的实验结果已提交至readme中，供参考。
