### ISSUE TITLE
some tensorflow api were changed in latest version

### ISSUE THREAD

**Issue by scdeng** [thunlp/CANE#3]
tf.batch_matmul() function was removed in latest version of tensorflow?  
tf.mul() was replaced by tf.multiply()
tf.pack was replaced by tf.stack()
so if latest version tensorflow was used, these functions should be replaced
changing tf.batch_matmul() to tf.matmul() may be complicated, parameters are different, 
cane.py at line 51
r1=tf.batch_matmul(ha_mul_rand,hB,adj_y=True) was replaced by 
r1=tf.matmul(ha_mul_rand, bB, transpose_a=False, transpose_b = True)

could you please post the intermediate running time outputs to the repo?

**Comment by tucunchao** [comment]
Below is the running command and outputs of our codes on Cora dataset. It seems that these functions in the old version can be also executed in r0.12. Note that, these codes rely on cuda-8.0. 
------------------------------------------------------------------------------------------------------------------
tcc@ubuntu:~/pythonspace/CANE/code$ python train.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
1000000
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:84:00.0
Total memory: 11.92GiB
Free memory: 11.81GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:84:00.0)
start training.......
epoch:  1  loss:  8881.31964111
epoch:  2  loss:  5238.34063721
epoch:  3  loss:  5184.52928162
epoch:  4  loss:  5167.45326233
epoch:  5  loss:  5145.23381042
epoch:  6  loss:  5124.60632324
