### ISSUE TITLE
Could you give a brief explanation about the result?

### ISSUE THREAD

**Issue by cailurus** [thunlp/CANE#4]

**Comment by tucunchao** [comment]
What does the result here refer to? The output in the command line, the output file or the experimental result in the paper?

**Comment by yunfeilongpoly** [comment]
Could you please provide the code about how to get the reported result in test data?

**Comment by yangyang20171121** [comment]
How to run the the same result as described in the  Tables and Figures of the paper?

**Comment by tucunchao** [comment]
负责实现本篇论文代码的共同一作Han Liu提供的代码实现，最终表示向量的计算方式与论文存在不一致，最开始提供的数据集也存在一些bug，Han Liu也一直没有进行回复该问题。所以我们在19年在Han Liu提供的代码和数据基础之上，提交了一些commits，进行了部分代码bug和数据的修复，目前最新版的实验结果已提交至readme中，供参考。
