### ISSUE TITLE
您好，在运行zhihu数据时，出现以下错误。

### ISSUE THREAD

**Issue by tangdouer** [thunlp/CANE#8]
1000000
start training.......
Traceback (most recent call last):
  File "train.py", line 39, in <module>
    text1,text2,text3=data.text[node1],data.text[node2],data.text[node3]
IndexError: index 10000 is out of bounds for axis 0 with size 10000
但是将graph.txt中带有10000的数据去掉之后就不会报错。请问这是什么原因。

**Comment by tucunchao** [comment]
不好意思，graph.txt里面下标都多加了1，现在已经更新

**Comment by tangdouer** [comment]
@tucunchao 好的，谢谢您！
